### ISSUE TITLE
Setup not working as expected

### ISSUE THREAD

**Issue by sjaghori** [jjnp/svelte-stage#1] opened 2022-12-07 15:14 UTC
**Describe the bug**
I created a sveltekit project using the template `npm create svelte@latest project-name`

Then I installed svelte stage and went through all getting started steps.

The `localhost:port/stage` route returns 500 whenever I visit that endpoint.

**Comment by jjnp** [comment] 2022-12-07 15:49
Will look into asap!

**Comment by jjnp** [comment] 2022-12-11 15:26
Have you tried waiting a bit and then refreshing the page?
On the newest svelte version I can reproduce the bug, but it seems to fix itself once the vite dependency optimization is through, so I think it has to do with that.

Can you try to exclude it from the dependency optimization in `vite.config.js` like so?
```javascript
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	},
	optimizeDeps: {
		exclude: ['svelte-stage']
	}
};

export default config;
```

Let me know if that fixes the issue. It would help to find out what's going on.

**Comment by sjaghori** [comment] 2022-12-13 17:03
I tried it again and now it optimizes on page load 😄 . 

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/30973909/207396496-7b1c1ad0-62ed-4a27-b244-02dda204eb12.png">


Can we exclude it from dep optimization without adding it to the svelte config, maybe lazy loading the library components? 
Something like:
```javascript
import('./Foo.svelte').then(module => {
  const cmp = module.default
  console.log(module.myNamedExport)
})
```

**Comment by jjnp** [comment] 2022-12-13 17:16
Potentially that's a fix, but I don't have any problem with vite optimizing the dependency. Vite optimizing dependencies makes sense after all...
The question is whether we can set it up in a way where it always works, before and after vite optimizes dependencies.
After vite optimized it, does it work as it should for you again?

**Comment by sjaghori** [comment] 2022-12-15 07:11
Yes, now it works as intended. Let's keep that in mind if it happens again.

**Comment by jjnp** [comment] 2022-12-28 21:49
Since stopping the dependency optimization seems to fix the problem, I'll close the issue. Feel free to re-open it should the problem re-surface.

**Closed as completed by jjnp** 2022-12-28 21:49 UTC
